using AngularApi.Controllers; using AngularApi.DTO; using AngularApi.Models; using AngularApi.Services.impelementation;
using FluentAssertions; using Microsoft.AspNetCore.Http; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore; using System.Security.Claims;
namespace AngularApi.Tests.Controllers;
public class PatientReviewsControllerTests : IDisposable {
  private readonly MedicalCenterDbContext _ctx; private readonly PatientReviewsController _ctl;
  public PatientReviewsControllerTests(){_ctx=new MedicalCenterDbContext(new DbContextOptionsBuilder<MedicalCenterDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options); _ctl=new PatientReviewsController(new PatientReviewService(_ctx,new OwnershipValidator())); _ctl.ControllerContext=new ControllerContext{HttpContext=new DefaultHttpContext{User=new ClaimsPrincipal(new ClaimsIdentity(new[]{new Claim(ClaimTypes.NameIdentifier,"patient1"),new Claim(ClaimTypes.Role,"admin")},"TestAuth"))}};}
  [Fact] public async Task GetPatientReviews_ReturnsAllReviews(){_ctx.PatientReviews.AddRange(new PatientReview{Id=1,PatientId="patient1",OverallRating=5,Patient=new Patient{Id="patient1",Name="J"}},new PatientReview{Id=2,PatientId="patient2",OverallRating=4,Patient=new Patient{Id="patient2",Name="S"}}); await _ctx.SaveChangesAsync(); (await _ctl.GetPatientReviews(new PaginationParameters())).Value!.Items.Should().HaveCount(2);}
  [Fact] public async Task GetPatientReview_ExistingId_ReturnsReview(){_ctx.PatientReviews.Add(new PatientReview{Id=1,PatientId="patient1",OverallRating=5}); await _ctx.SaveChangesAsync(); (((OkObjectResult)(await _ctl.GetPatientReview(1)).Result!).Value as PatientReview)!.OverallRating.Should().Be(5);}
  [Fact] public async Task GetPatientReview_NonExistingId_ReturnsNotFound()=>(await _ctl.GetPatientReview(1)).Result.Should().BeOfType<NotFoundResult>();
  [Fact] public async Task PutPatientReview_NonExistingId_ReturnsNotFound()=>(await _ctl.PutPatientReview(1,new UpdatePatientReviewDTO{DoctorId="d1",OverallRating=5})).Should().BeOfType<NotFoundResult>();
  [Fact] public async Task PutPatientReview_ExistingId_UpdatesReview(){_ctx.PatientReviews.Add(new PatientReview{Id=1,PatientId="patient1",DoctorId="d1",OverallRating=3}); await _ctx.SaveChangesAsync(); (await _ctl.PutPatientReview(1,new UpdatePatientReviewDTO{DoctorId="d1",OverallRating=5})).Should().BeOfType<NoContentResult>(); (await _ctx.PatientReviews.FindAsync(1))!.OverallRating.Should().Be(5);}
  [Fact] public async Task PostPatientReview_ValidInput_CreatesReview(){var c=((CreatedAtActionResult)(await _ctl.PostPatientReview(new CreatePatientReviewDTO{DoctorId="d1",OverallRating=5})).Result!).Value as PatientReview; c!.PatientId.Should().Be("patient1"); c.DoctorId.Should().Be("d1");}
  [Fact] public async Task DeletePatientReview_ExistingId_DeletesReview(){_ctx.PatientReviews.Add(new PatientReview{Id=1,PatientId="patient1"}); await _ctx.SaveChangesAsync(); (await _ctl.DeletePatientReview(1)).Should().BeOfType<NoContentResult>(); (await _ctx.PatientReviews.FindAsync(1)).Should().BeNull();}
  [Fact] public async Task DeletePatientReview_NonExistingId_ReturnsNotFound()=>(await _ctl.DeletePatientReview(1)).Should().BeOfType<NotFoundResult>();
  public void Dispose(){_ctx.Database.EnsureDeleted(); _ctx.Dispose();}
}
