sonar.projectKey=alekhyaakkiraju-droid_Medical_Center
sonar.organization=alekhyaakkiraju-droid

sonar.exclusions=**/node_modules/**,**/bin/**,**/obj/**,**/Migrations/**,**/api/generated/**,**/openapi/**,**/*.Designer.cs
sonar.cpd.exclusions=**/api/generated/**,**/openapi/**
