apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-center-api
  labels:
    app: medical-center-api
    tenant: opsera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-center-api
  template:
    metadata:
      labels:
        app: medical-center-api
        tenant: opsera
    spec:
      containers:
        - name: api
          image: PLACEHOLDER_API_ECR_URI
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__connection
              valueFrom:
                secretKeyRef:
                  name: medical-center-app-secrets
                  key: connection-string
            - name: Jwt__SecretKey
              valueFrom:
                secretKeyRef:
                  name: medical-center-app-secrets
                  key: jwt-secret
            - name: Jwt__ValidIssuer
              value: medical-center-dev
            - name: Jwt__ValidAudience
              value: medical-center-dev
            - name: Jwt__FrontendBaseUrl
              value: https://medical-center-yarp-dev.agent.opsera.dev
            - name: CorsSettings__AllowedOrigins__0
              value: https://medical-center-yarp-dev.agent.opsera.dev
            - name: EmailSettings__EmailUsername
              valueFrom:
                secretKeyRef:
                  name: medical-center-app-secrets
                  key: smtp-email-username
            - name: EmailSettings__EmailPassword
              valueFrom:
                secretKeyRef:
                  name: medical-center-app-secrets
                  key: smtp-email-password
            - name: GoogleAuth__ClientId
              valueFrom:
                secretKeyRef:
                  name: medical-center-app-secrets
                  key: google-auth-client-id
            - name: GoogleAuth__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: medical-center-app-secrets
                  key: google-auth-client-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 30
