apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-center-yarp
  labels:
    app: medical-center-yarp
    tenant: opsera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-center-yarp
  template:
    metadata:
      labels:
        app: medical-center-yarp
        tenant: opsera
    spec:
      containers:
        - name: yarp
          image: 792373136340.dkr.ecr.us-west-2.amazonaws.com/medical-center-yarp:b649494-30759578806
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: yarp-config
              mountPath: /app/appsettings.json
              subPath: appsettings.json
              readOnly: true
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: yarp-config
          configMap:
            name: medical-center-yarp-config
