using AngularApi.DTO;
using AngularApi.Models;
using AngularApi.Contracts.DTO; using AngularApi.Contracts.Models; using AngularApi.Contracts.Services.Interfaces; using AngularApi.Contracts.Services; using Microsoft.EntityFrameworkCore; using System.Security.Claims;
namespace AngularApi.Services.impelementation;
public class PatientReviewService : IPatientReviewService {
    private readonly MedicalCenterDbContext _context; private readonly IOwnershipValidator _ownershipValidator; private readonly ILogger<PatientReviewService> _logger;
    public PatientReviewService(MedicalCenterDbContext context, IOwnershipValidator ownershipValidator, ILogger<PatientReviewService> logger){_context=context;_ownershipValidator=ownershipValidator;_logger=logger;}
    public Task<PagedResult<ReviewDTO>> GetAllAsync(PaginationParameters pagination, CancellationToken ct=default)=>_context.PatientReviews.Select(r=>new ReviewDTO{Id=r.Id,PatientId=r.PatientId,DoctorId=r.DoctorId,IsReviewAnonymous=r.IsReviewAnonymous,WaitTimeRating=r.WaitTimeRating,BedsideMannerRating=r.BedsideMannerRating,OverallRating=r.OverallRating,Review=r.Review,IsDoctorRecommended=r.IsDoctorRecommended,ReviewDate=r.ReviewDate}).ToPagedResultAsync(pagination,ct);
    public Task<PagedResult<PatientDTO>> GetUniquePatientsAsync(PaginationParameters pagination, CancellationToken ct=default)=>_context.PatientReviews.Where(pr=>pr.Patient!=null).Select(pr=>new PatientDTO{PatientId=pr.Patient!.Id,Name=pr.Patient.UserName,Email=pr.Patient.Email,Image=pr.Patient.Image}).Distinct().ToPagedResultAsync(pagination,ct);
    public Task<PatientReviewDetailDTO?> GetByIdAsync(int id, CancellationToken ct=default)=>_context.PatientReviews.Where(r=>r.Id==id).SelectPatientReviewDetailDto().FirstOrDefaultAsync(ct);
    public async Task<PatientReview?> CreateAsync(CreatePatientReviewDTO dto, ClaimsPrincipal user, CancellationToken ct=default){var pid=user.FindFirstValue(ClaimTypes.NameIdentifier); if(string.IsNullOrEmpty(pid)||!_ownershipValidator.CanAccessPatientResource(user,pid))return null; var r=new PatientReview{DoctorId=dto.DoctorId,IsReviewAnonymous=dto.IsReviewAnonymous,WaitTimeRating=dto.WaitTimeRating,BedsideMannerRating=dto.BedsideMannerRating,OverallRating=dto.OverallRating,Review=dto.Review,IsDoctorRecommended=dto.IsDoctorRecommended,PatientId=pid,ReviewDate=DateTime.UtcNow,CreatedBy=pid}; _context.PatientReviews.Add(r); await _context.SaveChangesAsync(ct); return r;}
    public async Task<ResourceMutationResult> UpdateAsync(int id, UpdatePatientReviewDTO dto, ClaimsPrincipal user, CancellationToken ct=default){var e=await _context.PatientReviews.FindAsync([id],ct); if(e==null)return ResourceMutationResult.NotFound; if(!_ownershipValidator.CanAccessPatientReviewResource(user,e.PatientId!)){LogDenial(user,"PatientReview",id.ToString(),"Update"); return ResourceMutationResult.Forbidden;} e.DoctorId=dto.DoctorId;e.IsReviewAnonymous=dto.IsReviewAnonymous;e.WaitTimeRating=dto.WaitTimeRating;e.BedsideMannerRating=dto.BedsideMannerRating;e.OverallRating=dto.OverallRating;e.Review=dto.Review;e.IsDoctorRecommended=dto.IsDoctorRecommended; try{await _context.SaveChangesAsync(ct);return ResourceMutationResult.Success;}catch(DbUpdateConcurrencyException){if(!await _context.PatientReviews.AnyAsync(x=>x.Id==id,ct))return ResourceMutationResult.NotFound; throw;}}
    public async Task<ResourceMutationResult> DeleteAsync(int id, ClaimsPrincipal user, CancellationToken ct=default){var r=await _context.PatientReviews.FindAsync([id],ct); if(r==null)return ResourceMutationResult.NotFound; if(!_ownershipValidator.CanAccessPatientReviewResource(user,r.PatientId!)){LogDenial(user,"PatientReview",id.ToString(),"Delete"); return ResourceMutationResult.Forbidden;} _context.PatientReviews.Remove(r); await _context.SaveChangesAsync(ct); return ResourceMutationResult.Success;}
    private void LogDenial(ClaimsPrincipal user,string resourceType,string resourceId,string action)=>_logger.LogWarning("Ownership validation denied {ActorId} {ResourceType} {ResourceId} {Action} {Result}",user.FindFirstValue(ClaimTypes.NameIdentifier)??"unknown",resourceType,resourceId,action,"Denied");
}
