using AngularApi.DTO; using AngularApi.Models; using AngularApi.Services.Interfaces; using Microsoft.EntityFrameworkCore; using System.Security.Claims;
namespace AngularApi.Services.impelementation;
public class PatientReviewService : IPatientReviewService {
  private readonly MedicalCenterDbContext _context; private readonly IOwnershipValidator _ownershipValidator;
  public PatientReviewService(MedicalCenterDbContext context, IOwnershipValidator ownershipValidator){_context=context;_ownershipValidator=ownershipValidator;}
  public Task<PagedResult<ReviewDTO>> GetAllAsync(PaginationParameters pagination, CancellationToken ct=default)=>_context.PatientReviews.Select(r=>new ReviewDTO{Id=r.Id,PatientId=r.PatientId,DoctorId=r.DoctorId,IsReviewAnonymous=r.IsReviewAnonymous,WaitTimeRating=r.WaitTimeRating,BedsideMannerRating=r.BedsideMannerRating,OverallRating=r.OverallRating,Review=r.Review,IsDoctorRecommended=r.IsDoctorRecommended,ReviewDate=r.ReviewDate}).ToPagedResultAsync(pagination,ct);
  public Task<PagedResult<PatientDTO>> GetUniquePatientsAsync(PaginationParameters pagination, CancellationToken ct=default)=>_context.PatientReviews.Where(pr=>pr.Patient!=null).Select(pr=>new PatientDTO{PatientId=pr.Patient!.Id,Name=pr.Patient.UserName,Email=pr.Patient.Email,Image=pr.Patient.Image}).Distinct().ToPagedResultAsync(pagination,ct);
  public Task<PatientReview?> GetByIdAsync(int id, CancellationToken ct=default)=>_context.PatientReviews.FindAsync([id],ct).AsTask();
  public async Task<PatientReview?> CreateAsync(CreatePatientReviewDTO dto, ClaimsPrincipal user, CancellationToken ct=default){var pid=user.FindFirstValue(ClaimTypes.NameIdentifier); if(string.IsNullOrEmpty(pid)||!_ownershipValidator.CanAccessPatientResource(user,pid))return null; var r=new PatientReview{DoctorId=dto.DoctorId,IsReviewAnonymous=dto.IsReviewAnonymous,WaitTimeRating=dto.WaitTimeRating,BedsideMannerRating=dto.BedsideMannerRating,OverallRating=dto.OverallRating,Review=dto.Review,IsDoctorRecommended=dto.IsDoctorRecommended,PatientId=pid,ReviewDate=DateTime.UtcNow,CreatedBy=pid}; _context.PatientReviews.Add(r); await _context.SaveChangesAsync(ct); return r;}
  public async Task<bool> UpdateAsync(int id, UpdatePatientReviewDTO dto, ClaimsPrincipal user, CancellationToken ct=default){var e=await _context.PatientReviews.FindAsync([id],ct); if(e==null)return false; e.DoctorId=dto.DoctorId;e.IsReviewAnonymous=dto.IsReviewAnonymous;e.WaitTimeRating=dto.WaitTimeRating;e.BedsideMannerRating=dto.BedsideMannerRating;e.OverallRating=dto.OverallRating;e.Review=dto.Review;e.IsDoctorRecommended=dto.IsDoctorRecommended; try{await _context.SaveChangesAsync(ct);return true;}catch(DbUpdateConcurrencyException){if(!await _context.PatientReviews.AnyAsync(x=>x.Id==id,ct))return false; throw;}}
  public async Task<bool> DeleteAsync(int id, CancellationToken ct=default){var r=await _context.PatientReviews.FindAsync([id],ct); if(r==null)return false; _context.PatientReviews.Remove(r); await _context.SaveChangesAsync(ct); return true;}
}
